### ISSUE TITLE
[Header] Unmount not effective

### ISSUE THREAD

**Issue by tadamK** [get-focus/focus-application#36]
Hello,

When I am first on a page which contains a Header, and I go to a page which doesn't contain a header, the "old" header is still displayed.

It seems the following code is not effective : 

```
componentWillUnmount() {
    injectBarContentSummaryHeader(null);
    injectBarContentExpandedHeader(null);
    injectActionHeader(null);
}
```

"focus-application": "3.0.0-rc8"

**Comment by Ephrame** [comment]
I think it's a redux bug ....

**Comment by TomGallon** [comment]
same !

**Comment by TomGallon** [comment]
should we really inject null when unmouting the component ? i am not sure.
@Ephrame ?
