### ISSUE TITLE
[Message/Confirm Reducers] Useless console.log()

### ISSUE THREAD

**Issue by GuenoleK** [get-focus/focus-application#47]
## [Message/Confirm Reducers] Useless console.log()

There are some logs that are not used and not useful

https://github.com/get-focus/focus-application/blob/e66c37180510db01c789c7d87d16d8c2af362df2/src/messages/messages-reducer.js#L12

https://github.com/get-focus/focus-application/blob/e66c37180510db01c789c7d87d16d8c2af362df2/src/messages/messages-reducer.js#L19

https://github.com/get-focus/focus-application/blob/ce039c10c9c8044a59235cc711fd24314ee58e90/src/confirm/confirm-reducer.js#L11

**Comment by TomGallon** [comment]
thanks.
That's now ok
