### ISSUE TITLE
[Message center] Add CSS selector difference between different message type

### ISSUE THREAD

**Issue by rodolpheV** [get-focus/focus-application#50]
I would like to be able to put error messages in different format according to the type:
Error: Red background
Warning: Orange background
Info: blue background
Success: green background.
That's why I need css selector differentiation between types.

**Comment by TomGallon** [comment]
@rodolpheV 
that's already done. https://github.com/get-focus/focus-application/blob/master/src/messages/messages-actions.js
Please upgrade your lib
